apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-management-deployment
  labels:
    app: user-management-app
    version: v1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-app
      version: v1

  template:
    metadata:
      labels:
        app: user-management-app
        version: v1
    
    spec:
      containers:
        - name: user-management-app-container
          image: user-management-service:v1.100
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8052
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8052
            initialDelaySeconds: 60
            periodSeconds: 10
    
---

apiVersion: v1
kind: Service

metadata:
  name: user-management-service

spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8052
  selector:
    app: user-management-app
    version: v1