spring.application.name=booking

server.port=8051

inventory.base-url=http://localhost:8054

user.base-url=http://localhost:8052

payment.base-url=http://localhost:8053

logging.pattern.level=%5p [traceId=%X{traceId} bookingId=%X{bookingId} holdId=%X{holdId} paymentId=%X{paymentId}]
