apiVersion: v1
kind: Service

metadata:
  name: booking-api-gateway-service

spec:
  type: LoadBalancer
  ports:
    - port: 6500
      targetPort: 6500
  selector:
    app: bkng-api-gateway
    version: v1
